# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'textrank_v01.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
import platform

sys.path.append("..")
import nltk
import numpy as np
from glob import glob

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QFileDialog
from PyQt5.QtCore import pyqtSlot
from ui_mainwindow_v02 import Ui_MainWindow

# tokenizer import
from konlpy.tag import Okt, Komoran, Hannanum, Kkma

if platform.system() == "Windows":
    try:
        from eunjeon import Mecab
    except:
        print("please install eunjeon module")
else:  # Ubuntu일 경우
    from konlpy.tag import Mecab

from textrank import TextRank
from utils import pdf_to_text

# ignore warning
import warnings

warnings.filterwarnings(action="ignore")


STOPWORDS = nltk.corpus.stopwords.words("english")


class Summarizer(QMainWindow):
    def __init__(self):
        super(Summarizer, self).__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        # open file
        self.ui.pushButton.clicked.connect(self.get_file)

        # set language
        self.ui.comboBox.clear()
        self.ui.comboBox.addItems(["en", "ko"])

        # set num of kewyords
        self.ui.comboBox_2.clear()
        self.ui.comboBox_2.addItems(["5", "10", "15", "20"])

        # set num of keysents
        self.ui.comboBox_3.clear()
        self.ui.comboBox_3.addItems(["3", "5", "10", "15"])

        # text summarization
        self.summarize()
        # close the app
        self.close_app()

    @pyqtSlot()
    def get_file(self):
        self.file_name, _ = QFileDialog.getOpenFileName(
            self, "Open file", "c:\\", "PDF files (*.pdf)"
        )
        # print(self.file_name)
        self.ui.lineEdit.setText(self.file_name)

    def summarize(self):
        self.ui.pushButton_2.clicked.connect(self.click_summary)

    def close_app(self):
        self.ui.pushButton_3.clicked.connect(self.click_close)

    @pyqtSlot()
    def click_summary(self):
        self.language = str(self.ui.comboBox.currentText())
        self.top_k_word = int(self.ui.comboBox_2.currentText())
        self.top_k_sent = int(self.ui.comboBox_3.currentText())

        sents = pdf_to_text(self.file_name)

        # print(self.language, self.top_k_word, self.top_k_sent)
        if self.language == "ko":
            textrank = TextRank(language=self.language, tokenizer="mecab", stopwords=STOPWORDS)
        else:
            textrank = TextRank(language=self.language, tokenizer=None, stopwords=STOPWORDS)

        keywords = textrank.keywords(sents, topk=self.top_k_word)
        keysents = textrank.summarize(sents, topk=self.top_k_sent)

        self.ui.textBrowser.setText("\n".join(keysents))
        self.ui.textBrowser_2.setText(", ".join(keywords))

    @pyqtSlot()
    def click_close(self):
        self.close()


if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = Summarizer()
    window.show()

    sys.exit(app.exec_())
